const moment = require("moment")
module.exports = async function generateReport(sheet) {
    sheet.forEach((element) => (element["frenchDay"] = moment(element.date, 'DD/MM/YYYY').locale("fr").format("dddd").charAt(0).toUpperCase() + moment(element.date, 'DD/MM/YYYY').locale("fr").format("dddd").slice(1))); // Add day in French in each element
    let minimHours = sheet.length * 8.2
    let totalHours = moment.duration()
    console.log(`# Journal de travail du ${moment(sheet[0].date, "DD/MM/YYYY").toDate().toLocaleDateString('fr-FR')} au ${moment(sheet[sheet.length - 1].date, "DD/MM/YYYY").toDate().toLocaleDateString('fr-FR')}`)
    sheet.map(element => {
        totalHours.add(moment.duration(element.total));
        console.log(`
### ${element.frenchDay} ${element.date}

<table>
    <thead>
        <tr>
            <th>Heure d'arrivée</th>
            <th>Heure de départ (manger)</th>
            <th>Heure de retour</th>
            <th>Heure de départ</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>${element.morning_start}</td>
            <td>${element.morning_end}</td>
            <td>${element.afternoon_start}</td>
            <td>${element.afternoon_end}</td>
            <td>${element.total}</td>
        </tr>
    </tbody>
</table>
#### Description

${element.comment}
        `)
    })
    let hoursDiff = moment.utc(Math.round(moment.duration(totalHours.asHours() - minimHours, "hours").as('milliseconds'))).format('HH:mm')
    console.log(`
## Total : <u>${Math.floor(totalHours.asHours())}:${totalHours.minutes()}</u>

## Heures supplémentaires : <u>${hoursDiff}</u>
`)
    console.log(`<i><small>Generated by [jdt-generator](https://github.com/Azecko/jdt-generator) by [Azecko](https://github.com/Azecko)</small></i>`)
}